/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alumnos_notas;

import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author alumno
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        mNotas = new String[4][5];
        IniciarMatriz();
        
    }
    private void IniciarMatriz(){
        Random r = new Random();
        mNotas[0][1] = "Juan";
        mNotas[0][2] = "Pepe";
        mNotas[0][3] = "Alicia";
        mNotas[0][4] = "Andres";
        mNotas[1][0] = "Programacion";
        mNotas[2][0] = "Base de datos";
        mNotas[3][0] = "Ingles";
        for (int i = 1; i < mNotas.length; i++) {
            for (int j = 1; j < mNotas[i].length; j++) {
                int num = r.nextInt(11);
                mNotas[i][j]=Integer.toString(num);
            }
        }
       
 
    }
   
    private double mediaAlumno(String nombre){
        double media=0;
        
        for (int i = 1; i < mNotas[0].length; i++) {
            if(mNotas[0][i].equalsIgnoreCase(nombre)){
                for (int j = 1; j < mNotas.length; j++) {
                    media+=Double.parseDouble(mNotas[j][i]);
                    System.out.println(mNotas[j][i]);
                }
            }
        }
        media=media/3;
        System.out.println(media);
        return media;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldAsignatura = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonNotas = new javax.swing.JButton();
        jButtonMedia = new javax.swing.JButton();
        jButtonAlumnos = new javax.swing.JButton();
        jButtonMediaTotal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jButtonNotas.setText("Notas Alumno");
        jButtonNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNotasActionPerformed(evt);
            }
        });

        jButtonMedia.setText("Media Asignatura");
        jButtonMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMediaActionPerformed(evt);
            }
        });

        jButtonAlumnos.setText("Todos Los alumnos");
        jButtonAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlumnosActionPerformed(evt);
            }
        });

        jButtonMediaTotal.setText("Media Total");
        jButtonMediaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMediaTotalActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAsignatura)
                            .addComponent(jButtonAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonMedia, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jButtonNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMediaTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(54, 54, 54))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(294, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButtonNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMediaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(347, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNotasActionPerformed
       double media=0;
       String aux=""; 
        for (int i = 1; i < mNotas[0].length; i++) {
            if(mNotas[0][i].equalsIgnoreCase(jTextFieldNombre.getText())){
                for (int j = 1; j < mNotas.length; j++) {
                    media+=Double.parseDouble(mNotas[j][i]);
                    aux+=mNotas[j][0]+" "+mNotas[j][i]+"\n";
                }
            }
        }
        media=media/3;
        
        aux+="media : "+media;
        jTextPane.setText(aux);
    }//GEN-LAST:event_jButtonNotasActionPerformed

    private void jButtonMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMediaActionPerformed
       double media=0;
       String aux=""; 
        for (int i = 1; i < mNotas.length; i++) {
            if(mNotas[i][0].equalsIgnoreCase(jTextFieldAsignatura.getText())){
                for (int j = 1; j < mNotas[i].length; j++) {
                    media+=Double.parseDouble(mNotas[i][j]);
                    aux+=mNotas[0][j]+" "+mNotas[i][j]+"\n";
                }
            }
        }
        media=media/4;
        
        aux+="media : "+media;
        jTextPane.setText(aux);
    }//GEN-LAST:event_jButtonMediaActionPerformed

    private void jButtonMediaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMediaTotalActionPerformed
        double media=0;
       String aux=""; 
        for (int i = 1; i < mNotas.length; i++) {
            for (int j = 1; j < mNotas[i].length; j++) {
                media+=Double.parseDouble(mNotas[i][j]);
            }
   
            
        }
        media=media/12;
        
        aux+="media : "+media;
        jTextPane.setText(aux);
    }//GEN-LAST:event_jButtonMediaTotalActionPerformed

    private void jButtonAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlumnosActionPerformed
        String aux="";
        for (int i = 0; i < mNotas.length; i++) {
            for (int j = 0; j < mNotas[i].length; j++) {
                aux+=mNotas[i][j]+" ";
            }
            aux+=" \n";
        }
        jTextPane.setText(aux);
    }//GEN-LAST:event_jButtonAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }
    private String mNotas[][];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlumnos;
    private javax.swing.JButton jButtonMedia;
    private javax.swing.JButton jButtonMediaTotal;
    private javax.swing.JButton jButtonNotas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAsignatura;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextPane jTextPane;
    // End of variables declaration//GEN-END:variables
}
